version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
jobs:
  test:
    docker:
    - image: circleci/golang:1.13

    working_directory: /go/src/github.com/codechaitu/api
    environment:
      GO111MODULE: "on"
    steps:
    - checkout
    - run:
        name: Get dependencies
        command: |
          go mod vendor
    - run:
       name: Run test cases
       command: |
          go test ./...

workflows:
  test and deploy:
    jobs:
    - test
    - heroku/deploy-via-git:
        requires:
        - test
        filters:
          branches:
            only: master
